Migrate Anbox Streaming SDK to GitHub
canonical/anbox-streaming-sdk pull request #2
Opened 2024-02-19 12:17 UTC by adglkh

2024-02-21 10:31 UTC, morphis requested changes

2024-02-21 10:31 UTC, morphis commented on js/LICENSE
Why do we have this a second time? We should have this once at the top of the repository?

2024-02-21 10:31 UTC, morphis commented on examples/scripts/build-with-docker.sh
> +#
We need to update the copyright header to reflect Apache-2.0

2024-02-21 10:31 UTC, morphis commented on examples/scripts/clean-build.sh
> +#
See above

2024-02-21 10:31 UTC, morphis commented on js/run-tests.sh
> +# Copyright 2021 Canonical Ltd.  All rights reserved.
See above

2024-02-21 10:31 UTC, morphis commented on js/tests/unit/run-tests.sh
> +#
See above

2024-02-21 10:31 UTC, morphis commented on scripts/build.sh
> +# Copyright 2019 Canonical Ltd.  All rights reserved.
See above

2024-02-21 10:31 UTC, morphis commented on scripts/gen-version.sh
> +# Copyright 2020 Canonical Ltd.  All rights reserved.
See above

2024-02-21 10:31 UTC, morphis commented on scripts/run-tests.sh
> +# Copyright 2020 Canonical Ltd.  All rights reserved.
See above

2024-02-21 10:31 UTC, morphis commented on scripts/streaming-sdk-files.allowlist
This is no longer needed

2024-02-21 10:31 UTC, morphis commented on scripts/validate.sh
This is no longer needed

2024-02-22 04:36 UTC, adglkh commented on js/LICENSE
I think the original idea is to create a release tarball without cp the license around(from the top to the nested folder)
I can drop this for simplicity.

2024-02-22 04:36 UTC, adglkh commented on scripts/streaming-sdk-files.allowlist
To me, the `streaming-sdk-files.allowlist` and the following `scripts/validate.sh` are still required to ensure there are no other pieces of needless files to be injected into the resulting zip tarball.
The content of the resulting zip tarball won't include every piece of source files in this repo(E.g. scripts/*, example/scripts/*) after this PR is merged and it will remain the same as the current layout.

2024-02-22 04:36 UTC, adglkh commented on examples/scripts/build-with-docker.sh
> +#
Thanks for pointing this out!
Will fix.

2024-02-22 06:07 UTC, jat-canonical reviewed
A few comments

2024-02-22 06:07 UTC, jat-canonical commented on examples/js/anbox-stream-sdk.js
Has this been moved under `js/`? as I cannot see it there.

2024-02-22 06:07 UTC, jat-canonical commented on examples/scripts/build-with-docker.sh
Examples of using the sdk make sense but why do we need example scripts for building it ?

2024-02-22 06:26 UTC, adglkh commented on examples/js/anbox-stream-sdk.js
The layout in the resulting release tarball/artifact is identical to what we have today(E..g [the artifact]( https://github.com/adglkh/anbox-streaming-sdk/actions/runs/7999651120) includes all contents after this change) but not 1:1 mapping from the source layout in the repo after this MP got merged.

I'd suggest taking a look AC074 spec for details.

2024-02-22 06:27 UTC, adglkh commented on .github/workflows/ci.yaml
> +      uses: actions/checkout@v2
Okay, I can change that later on.

2024-02-22 06:39 UTC, jat-canonical commented on examples/js/anbox-stream-sdk.js
yes but what i mean is i cannot see the js source files at all under js.

2024-02-22 07:03 UTC, adglkh commented on examples/js/anbox-stream-sdk.js
We only ship one piece of js file in the trunk, and cp it to each js folder when creating a release tarball.
In this way, if any code change is made to the js file, we won't replicate the same change to other copy of js files.
See:
https://github.com/canonical/anbox-streaming-sdk/pull/2/files#diff-3d64996115d0ac3b74e36f57ce6b00d6b4982614c41b1ed39eab8ef43b2e9a2bR68

2024-02-22 07:49 UTC, jat-canonical commented on examples/js/anbox-stream-sdk.js
alright makes sense

2024-02-22 19:16 UTC, morphis requested changes

2024-02-22 19:16 UTC, morphis commented on scripts/build.sh
> +    --create-tarball)
As mentioned above I don't we need to create a tarball at all. What do we win by doing that? If correctly tag the git repository will automatically create an archive for each release for us without us doing anything,

2024-02-23 03:54 UTC, adglkh commented on examples/js/anbox-stream-sdk.js
1. Using the git archive feature provided by Github results in creating a zip tarball for the entire repository, which includes quite a few needless contents, such as scripts/. After this PR is merged, the content layout of this repository varies and is not identical to what we want to deliver in our release tarball (Check what we currently have in this repo vs the sources in the PR). 
2. With the tarball archived with git, which missing js SDK file in all examples. users have to manually copy the js sdk file into each example repository before building and running it, which is not straight forward for the end user (given that we only maintain one piece of js file in this repository.)
3. For the same reason in 2), users must also build the AAR and APK files themselves before being able to play with Android examples.

Hence as a release tarball, the out-of-the-box experience is not satisfactory
That's why the `--create-tarball` cli parameter is introduced into the build script to generate the proper release tarball, align with what we deliver today.

2024-02-23 03:55 UTC, adglkh commented on examples/scripts/build-with-docker.sh
We can do that.

2024-02-23 07:57 UTC, morphis approved these changes
LGTM lets merge to get a first version in place. Any cleanup can happen afterwards.

2024-02-23 07:57 UTC, merged