feat(e2e-tests): added e2e tests (setup, teardown and join session spec) [WD-11275]
canonical/anbox-streaming-sdk pull request #30
Opened 2024-05-28 06:12 UTC by lorumic

Added e2e tests: setup, teardown and join session spec.

Fixes [WD-11275](https://warthogs.atlassian.net/browse/WD-11275)

2024-05-28 06:55 UTC, morphis requested changes

2024-05-28 06:55 UTC, morphis commented on .github/workflows/ci.yaml
> +        sudo chmod 0666 anbox-cloud.key
I am not sure why you need 0666 here. Aren't the tests running with the same user you create the key/cert here?

2024-05-28 06:55 UTC, morphis commented on .github/workflows/ci.yaml
> +        sudo apt install -y anbox-modules-dkms-121 linux-generic-hwe-22.04
```suggestion
        sudo apt install -y anbox-modules-dkms-122 linux-generic-hwe-22.04
```

It would be even better if we can calculate the package name based on `.base_version`

2024-05-28 06:55 UTC, morphis commented on .github/workflows/ci.yaml
> +        channel: latest/edge
Why latest/edge? We currently only support 5.0 LTS. One of the next releases will add 5.21 support.

2024-05-28 06:55 UTC, morphis commented on .github/workflows/ci.yaml
> +        sudo lxc storage create local dir
Why using `dir` storage backend here? Is that faster on the Github/self hosted runners?

2024-05-28 06:55 UTC, morphis commented on .github/workflows/ci.yaml
> +        sudo microbox.amc image add jammy:android13:amd64 jammy:android13:amd64
Why is this needed?

2024-05-28 06:55 UTC, morphis commented on .github/workflows/ci.yaml
> +        sudo chmod 0666 .env.local
See comment above, why do you need 0666 here and create as root?

2024-05-28 06:55 UTC, morphis commented on .github/workflows/ci.yaml
> +        node-version: 20
Why 20? Isn't 22 the latest version?

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/eslint.config.mjs
> +import globals from "globals";
Needs a copyright header

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/fixtures/constants.js
> +const APP_NAME = "streaming-sdk-e2e-tests";
Needs a copyright header

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/global-setup.js
> +import { chromium, expect } from "@playwright/test";
Needs a copyright header

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/global-teardown.js
> +import { expect } from "@playwright/test";
Needs a copyright header

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/index.html
> +<!doctype html>
Needs a copyright header

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/playwright.config.js
> +import { defineConfig, devices } from "@playwright/test";
Needs a copyright header

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/playwright.config.js
> +// require('dotenv').config();
Can this be dropped if not needed?

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/playwright.config.js
> +    // baseURL: 'http://127.0.0.1:3000',
Can this be dropped if not needed?

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/playwright.config.js
> +    // },
Can this be dropped if not needed?

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/server.js
> +const express = require("express");
Needs a copyright header

2024-05-28 06:55 UTC, morphis commented on js/tests/e2e/tests/join.spec.js
> +import { test, expect } from "@playwright/test";
Needs a copyright header

2024-05-28 07:08 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo chmod 0666 anbox-cloud.key
This was imported as is from the dashboard [workflow](https://github.com/canonical/ams/blob/main/.github/workflows/ui-e2e.yaml), which @edlerd prepared. Can you please answer this question? @edlerd

2024-05-28 07:08 UTC, lorumic commented on .github/workflows/ci.yaml
> +        channel: latest/edge
This was imported as is from the dashboard [workflow](https://github.com/canonical/ams/blob/main/.github/workflows/ui-e2e.yaml), which @edlerd prepared. Can you please answer this question? @edlerd

2024-05-28 07:08 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo lxc storage create local dir
This was imported as is from the dashboard [workflow](https://github.com/canonical/ams/blob/main/.github/workflows/ui-e2e.yaml), which @edlerd prepared. Can you please answer this question? @edlerd

2024-05-28 07:09 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo microbox.amc image add jammy:android13:amd64 jammy:android13:amd64
This and the following lines make sure that the image is already active when we run the actual Playwright tests, and we don't need to download them on application creation (which would increase the test duration).

2024-05-28 07:11 UTC, lorumic commented on .github/workflows/ci.yaml
> +        node-version: 20
Node 20 is the latest LTS as of now.

2024-05-28 07:14 UTC, edlerd reviewed
This looks pretty good. Some ideas and observations below.

2024-05-28 07:14 UTC, edlerd commented on js/tests/e2e/tests/join.spec.js
> +  await page.goto(`http://127.0.0.1:2999?sessionId=${process.env.SESSION_ID}`);
```suggestion
  await page.goto(`/?sessionId=${process.env.SESSION_ID}`);
```
We should rely on the base url in playwright config, not to repeat it in each test.

2024-05-28 07:14 UTC, edlerd commented on .github/workflows/ci.yaml
Probably better to keep the e2e job in a dedicated file like and reference it like https://github.com/canonical/ams/blob/main/.github/workflows/pr.yaml

2024-05-28 07:14 UTC, edlerd commented on js/tests/e2e/playwright.config.js
> +// require('dotenv').config();
```suggestion
```

2024-05-28 07:14 UTC, edlerd commented on js/tests/e2e/playwright.config.js
> +    // baseURL: 'http://127.0.0.1:3000',
```suggestion
    baseURL: 'http://127.0.0.1:3000',
```
This should be set. Maybe define a constant to use here and in the teardown / setup script as well.

2024-05-28 07:14 UTC, edlerd commented on js/tests/e2e/server.js
> +const port = 2999;
I think the port should come from `.env` as well. We can add a .env file and commit it with the default port value of 2999.

Then we can use it here and construct the base url fixture for the playwright test config and wherever we need the port as well.

2024-05-28 07:14 UTC, edlerd commented on js/tests/e2e/run-tests.sh
> +npx playwright test
Should we run those commands in docker like we do for the unit tests?

That would unify the npm version. Currently, it relies on the host npm being available. We could then drop the install npm from the workflow.

2024-05-28 07:16 UTC, edlerd commented on .github/workflows/ci.yaml
> +        sudo lxc storage create local dir
It is the driver with the least dependencies that always works. I didn't benchmark performance, we could switch this out if another one is faster.

2024-05-28 07:17 UTC, edlerd commented on .github/workflows/ci.yaml
> +        channel: latest/edge
We can switch the channel to the one Anbox expects.

2024-05-28 07:19 UTC, edlerd commented on .github/workflows/ci.yaml
> +        sudo chmod 0666 anbox-cloud.key
There was an access error without this. I don't remember the exact details. You can remove those two lines to get the details.

2024-05-28 07:27 UTC, lorumic commented on js/tests/e2e/global-setup.js
> +  const page = await browser.newPage();
It's already at the closest point to where it is used. The next line is:
```
const isAppReady = await waitForAppReady(page);
```
We need `page` there, and we want to reuse that same page for `waitForSessionActive` later on.

2024-05-28 07:29 UTC, lorumic commented on .github/workflows/ci.yaml
It's much better integrated with the CI job this way. It also reuses the same logic in this step:
```
    - name: Run tests
      run: |
        ./scripts/run-tests.sh
```

2024-05-28 07:32 UTC, lorumic commented on js/tests/e2e/run-tests.sh
> +npx playwright test
I don't think it's possible, we need all the infrastructure (lxd, microbox, etc), not only npm, inside docker, for it to work. I'd keep this as close as the dashboard workflow if possible, keeping docker out of this.

2024-05-28 07:34 UTC, lorumic commented on js/tests/e2e/server.js
> +const port = 2999;
Why in .env? Let's just put the port as well in the constants file and make our life simpler. It will always be used together with the base URL anyway.

2024-05-28 07:39 UTC, lorumic commented on js/tests/e2e/fixtures/constants.js
> +exports.IMAGE_NAME = IMAGE_NAME;
Nope, this doesn't work in CJS.

2024-05-28 07:47 UTC, morphis commented on .github/workflows/ci.yaml
> +        sudo lxc storage create local dir
There is a trade-off with dir in that you need to always copy the entire rootfs or extract the rootfs tarball each time you start a new instance. In case of a loop based storage pool you can easily depend on COW but potentially have slower IO. I think it's definitely worth trying using a ZFS based pool.

2024-05-28 07:49 UTC, morphis commented on js/tests/e2e/run-tests.sh
> +npx playwright test
Why would you need all of LXD, microbox, etc inside docker? Isn't playwright just talking to the things over IP?

2024-05-28 07:49 UTC, lorumic commented on .github/workflows/ci.yaml
> +        channel: latest/edge
That would be `5.0/stable`, right?

2024-05-28 07:51 UTC, lorumic commented on js/tests/e2e/run-tests.sh
> +npx playwright test
I'm afraid this goes beyond my understanding. If you have a concrete suggestion on what you want to see done here, we can try that. Otherwise this is what I could come up with with my current skills and knowledge.

2024-05-28 08:15 UTC, lorumic commented on js/tests/e2e/run-tests.sh
> +npx playwright test
Need more info, will sync with @edlerd on this point.

2024-05-28 08:50 UTC, edlerd commented on js/tests/e2e/run-tests.sh
> +npx playwright test
LXD and microbox are not started, they will need to accessed by IP, right. We would just run playwright wrapped in a docker container.

2024-05-28 08:51 UTC, edlerd commented on js/tests/e2e/server.js
> +const port = 2999;
Can also be in a constants file. Though might be better to keep the config in one location, hence I was suggesting the .env file.

2024-05-28 08:53 UTC, edlerd commented on .github/workflows/ci.yaml
Maybe it is better to split the unit and e2e test workflows and they can both run their entrypoint scripts. I am not too opinionated on this one though.

2024-05-28 08:54 UTC, edlerd commented on js/tests/e2e/fixtures/constants.js
> +exports.IMAGE_NAME = IMAGE_NAME;
Maybe use the cjs file extension then?

2024-05-28 08:59 UTC, lorumic commented on js/tests/e2e/server.js
> +const port = 2999;
The .env.local file contains only config related to AMS and ASG, so it would be out of place there. The constants file, instead, has the base URL, which is directly connected to the port (and needs it). I moved the server port constant there.

2024-05-28 09:59 UTC, lorumic commented on .github/workflows/ci.yaml
Let's maybe hear from @morphis what he prefers here?

2024-05-28 10:03 UTC, lorumic commented on js/tests/e2e/run-tests.sh
> +npx playwright test
Done (thanks @edlerd )

2024-05-28 11:19 UTC, adglkh requested changes

2024-05-28 11:19 UTC, adglkh commented on .github/workflows/ci.yaml
> +        sudo apt install -y anbox-modules-dkms-122 linux-generic-hwe-22.04
1. Why not load the installed kernel modules after installing the anbox-modules-dkms package?
2. Why do we need to install hwe kernel? if there is a need, a reboot is required so the hwe kernel will be in use instead after that?

2024-05-28 11:19 UTC, adglkh commented on .github/workflows/ci.yaml
> +        sudo microbox.amc config set images.auth "bearer:$(sudo cat /var/lib/ubuntu-advantage/private/machine-token.json | jq -r '.resourceTokens[] | select(.type=="anbox-images").token')"
@morphis  Is it fine to leak the way how to fetch the token that is used to access our image server?

2024-05-28 11:19 UTC, adglkh commented on .github/workflows/ci.yaml
> +        touch .env.local
Can be dropped

2024-05-28 11:23 UTC, lorumic commented on .github/workflows/ci.yaml
> +        touch .env.local
Not sure what you want to drop here?

2024-05-28 11:24 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo apt install -y anbox-modules-dkms-122 linux-generic-hwe-22.04
This was imported as is from the dashboard [workflow](https://github.com/canonical/ams/blob/main/.github/workflows/ui-e2e.yaml), which @edlerd prepared. Can you please answer these questions? @edlerd

2024-05-28 11:48 UTC, lorumic commented on .github/workflows/ci.yaml
> +        touch .env.local
Ah, I see! Thanks for pointing this out. Will remove it.

2024-05-28 14:11 UTC, ajanon requested changes
Some comments from me. I don't have much to say for the JS files, as I don't feel experienced enough in JS to review them.

Also, would you mind splitting this in multiple commits? Some of these changes are their own thing:
- adding a line to .gitignore
- adding the e2e directory and everything required for testing (js/tests/e2e/run-tests.sh, changes to js/run-tests.sh)
- changing the CI workflow to run them

Or maybe you wanted to wait after the first round of reviews to do that?

2024-05-28 16:58 UTC, lorumic commented on .github/workflows/ci.yaml
> +        echo "ASG_API_TOKEN=$(sudo cat /var/snap/microbox/common/dashboard/config.yaml | grep ASG_API_TOKEN | cut -d ' ' -f2)" >> .env.local
Yeah, let's keep things simpler without adding other packages.

2024-05-28 16:59 UTC, lorumic commented on .gitignore
> +.idea
This was @edlerd's request. I will remove it for now, then add it at the end with a separate commit.

2024-05-28 18:14 UTC, ajanon commented on .gitignore
> +.idea
Thanks!

2024-05-28 18:15 UTC, ajanon approved these changes
LGTM

2024-05-29 06:53 UTC, morphis commented on .github/workflows/ci.yaml
> +        sudo microbox.amc config set images.auth "bearer:$(sudo cat /var/lib/ubuntu-advantage/private/machine-token.json | jq -r '.resourceTokens[] | select(.type=="anbox-images").token')"
There is no secret in here, so not a problem at all.

2024-05-29 06:54 UTC, morphis commented on .github/workflows/ci.yaml
I think being able to run both in parallel makes sense, specifically as the e2e tests may take much longer.

2024-05-29 07:42 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo chmod 0666 anbox-cloud.key
Removed them and there is no access error.

2024-05-29 07:43 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo lxc storage create local dir
Switching to ZFS driver for the pool. Marking as resolved.

2024-05-29 07:44 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo chmod 0666 .env.local
Removed these as well. Marking as resolved.

2024-05-29 07:44 UTC, lorumic commented on .github/workflows/ci.yaml
Ok, I will split them.

2024-05-29 07:45 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo apt install -y anbox-modules-dkms-122 linux-generic-hwe-22.04
Addressed both points. Marking as resolved.

2024-05-29 09:31 UTC, lorumic commented on .github/workflows/ci.yaml
> +        sudo microbox.amc image add jammy:android13:amd64 jammy:android13:amd64
I removed this now, because with the dedicated workflow the image does not become active in time, as there is no build step anymore (which used to take ~5 minutes before, allowing plenty of time for the image to be fully downloaded).

2024-05-29 09:37 UTC, lorumic commented
@morphis @adglkh @ajanon Thanks for your comments and suggestions. I think I have addressed all of them but please let me know if I forgot anything. Otherwise, this is now ready for another round of review from your side. The check will fail here as I cannot access the secret from my fork, but you can see it is now passing [here](https://github.com/lorumic/anbox-streaming-sdk/actions/runs/9283466155/job/25543740107).

@edlerd Feel free to have another pass as well, and don't worry, I'll add the `.idea` to the `.gitignore` just in time before merging - as a separate commit as @ajanon suggested. :)

2024-05-29 09:47 UTC, adglkh approved these changes
LGTM

2024-05-29 10:20 UTC, ajanon approved these changes
LGTM

2024-05-29 10:42 UTC, edlerd approved these changes
LGTM, some tiny improvement ideas below.

2024-05-29 10:42 UTC, edlerd commented on .github/workflows/e2e.yaml
> +    - name: Generate keys and allow permissions
```suggestion
    - name: Generate keys
```

2024-05-29 10:42 UTC, edlerd commented on js/tests/e2e/playwright.config.js
> +    ignoreHTTPSErrors: true,
```suggestion
```
We are not using ssl I think.

2024-05-29 10:42 UTC, edlerd commented on js/tests/e2e/playwright.config.js
> +    url: "http://127.0.0.1:2999",
```suggestion
    url: BASE_URL,
```
Can we use the base url here?

2024-05-29 10:42 UTC, edlerd commented on .github/workflows/e2e.yaml
> +on:
```suggestion
name: E2e tests
on:
```
Should give this workflow a nice name

2024-05-29 10:44 UTC, lorumic commented on js/tests/e2e/playwright.config.js
> +    ignoreHTTPSErrors: true,
At least when running the tests locally, for sure we are. So we need this or Playwright will get stuck when trying to join a session.

2024-05-29 10:46 UTC, lorumic commented on js/tests/e2e/playwright.config.js
> +    url: "http://127.0.0.1:2999",
Yes, nice catch!

2024-05-29 10:46 UTC, lorumic commented on .github/workflows/e2e.yaml
> +    - name: Generate keys and allow permissions
Great catch :)

2024-05-29 10:47 UTC, lorumic commented on .github/workflows/e2e.yaml
> +on:
Ok, wasn't sure as the one we had for the dashboard was anonymous. Will add the name there.

2024-05-29 11:29 UTC, edlerd approved these changes

2024-05-31 12:08 UTC, morphis approved these changes
LGTM but left some questions inline

2024-05-31 12:08 UTC, morphis commented on .github/workflows/e2e.yaml
> +      - '**'
Why do we run on merge (push) and nightly?

2024-05-31 12:08 UTC, morphis commented on .github/workflows/e2e.yaml
> +        sudo snap install microbox --channel=latest/candidate
Can you add a FIXME comment and record a bug that this should switch back to latest/edge ASAP as soon as the issues are resolved?

2024-05-31 12:08 UTC, morphis commented on .github/workflows/e2e.yaml
> +        sudo microbox.amc image add jammy:android13:amd64 jammy:android13:amd64
Do we plan to run the tests for arm64 as well?

2024-05-31 15:00 UTC, lorumic commented on .github/workflows/e2e.yaml
> +      - '**'
Good point - there is no specific reason actually. I'm just mimicking (= copy-pasting from) what we do for the CI build workflow. Please let me know if this makes little sense, and feel free to propose a different running conditions for the e2e tests.

2024-05-31 15:13 UTC, lorumic commented on .github/workflows/e2e.yaml
> +        sudo snap install microbox --channel=latest/candidate
Yes, I can do that. We can also wait for the fix that you've prepared for microbox, and merge this one after that (and then reverting back to edge before merging here). There's no rush. Let me know how you prefer to proceed.

2024-06-03 08:14 UTC, lorumic commented on .github/workflows/e2e.yaml
> +        sudo microbox.amc image add jammy:android13:amd64 jammy:android13:amd64
I updated the job name from the (redundant) "e2e-tests" to "microbox, amd64" for better identification of the tool and architecture of the current test suite.

2024-06-03 08:15 UTC, lorumic commented on .github/workflows/e2e.yaml
> +        sudo snap install microbox --channel=latest/candidate
Added the FIXME comment :)

2024-06-04 19:22 UTC, morphis approved these changes
LGTM

2024-06-04 19:22 UTC, morphis commented on .github/workflows/e2e.yaml
> +        sudo snap install microbox --channel=latest/candidate
This should have been fixed. Can you either update the PR or send a follow up one to switch us back to latest/edge?

2024-06-04 19:44 UTC, morphis approved these changes
LGTM

2024-06-04 19:58 UTC, lorumic commented
Cool, the workflow run passed on the [fork](https://github.com/lorumic/anbox-streaming-sdk/actions/runs/9373288727). This is ready to merge. :)

2024-06-04 19:59 UTC, lorumic commented on .github/workflows/e2e.yaml
> +        sudo snap install microbox --channel=latest/candidate
Done, thanks for the quick fix!

2024-06-05 14:28 UTC, merged