fix(ci) run end to end tests on pull request target event
canonical/anbox-streaming-sdk pull request #37
Opened 2024-06-24 16:07 UTC by edlerd

2024-06-25 12:12 UTC, morphis requested changes

2024-06-25 12:12 UTC, morphis commented on .github/workflows/e2e.yaml
> +      run: git checkout ${{ github.event.pull_request.head.ref }}
We cannot do that without approval. We *MUST* define an explicit environment the job should run on, see https://docs.github.com/en/actions/using-jobs/using-environments-for-jobs. We can then configure the environment in the repository settings to require explicit approval before this can run. Otherwise we do not really solve anything here, even worse, we now allow everyone to read our secrets :-)

2024-06-25 12:26 UTC, edlerd commented on .github/workflows/e2e.yaml
> +      run: git checkout ${{ github.event.pull_request.head.ref }}
We need to read secrets in the flow below. I thought it is okay to run this way, because we require manual approval for outside contributions in the [repository settings](https://github.com/canonical/anbox-streaming-sdk/settings/actions). So any code that is run has gone through a review beforehand.

2024-06-25 12:29 UTC, edlerd commented on .github/workflows/e2e.yaml
> +      run: git checkout ${{ github.event.pull_request.head.ref }}
Or do you mean we should move the pro token to be an environment secret and use an environment here to access it?
We can do that, though that is the only secret we have at the moment.

2024-06-25 13:31 UTC, morphis commented on .github/workflows/e2e.yaml
> +      run: git checkout ${{ github.event.pull_request.head.ref }}
> Or do you mean we should move the pro token to be an environment secret and use an environment here to access it?

Yes, that's what I discussed last with @lorumic from what I recall to make sure this is always explicitly approved. I am not sure if approval for outside contributors is a one-off or has to happen for every update to the PR. If it has to happen for every update to the PR this can work as well but I personally feel much better if we make the e2e test workflow optional for contributions (e.g. not have it as part of the required checks to pass) and then ask for explicit approval via an environment.

2024-06-25 14:09 UTC, edlerd commented on .github/workflows/e2e.yaml
> +      run: git checkout ${{ github.event.pull_request.head.ref }}
I added the environment to the job and set up an environment secret. Hope I understood you correctly?

2024-06-25 18:41 UTC, morphis commented on .github/workflows/e2e.yaml
> +      run: git checkout ${{ github.event.pull_request.head.ref }}
That looks good, thanks!

2024-06-25 18:43 UTC, morphis requested changes
Overall LGTM. One small question in line. 

Also, can you update the commit message? Please drop the JIRA ticket number as that has no meaning to the public, also please put a justification/description of why the change is being implemented in the description so this can be understood by others.

2024-06-25 18:43 UTC, morphis commented on .github/workflows/e2e.yaml
> +        echo "GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}"
What is this needed for? Just for debugging?

2024-06-26 02:01 UTC, adglkh approved these changes
LGTM. (one comment though)

2024-06-26 02:01 UTC, adglkh commented on .github/workflows/e2e.yaml
> +        echo "GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}"
I guess it just prints out branch information for the context of this workflow.
Honestly I don't see much value in keeping it here.

2024-06-26 10:29 UTC, edlerd commented on .github/workflows/e2e.yaml
> +        echo "GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}"
Removed this step.

2024-06-26 10:32 UTC, edlerd commented
> Please drop the JIRA ticket number

This has meaning for us, as our JIRA automatically links to relevant commits and updates the ticket status on PR open (ticket is passed into review state) and on PR merge (ticket is marked as done). I kept the reference in a last line of the commit message, so it shouldn't disturb on reading the commit log.

2024-06-26 10:37 UTC, morphis approved these changes

2024-06-26 10:37 UTC, morphis commented on .github/workflows/e2e.yaml
We do not see the e2e flow running anymore for this PR as we now switched to `pull_request_target` and as the workflow doesn't exist within the target repository, it is never run. So this is OK.

2024-06-26 10:37 UTC, merged