feat(e2e): add e2e tests for stream disconnect, vhal methods [WD-11812]
canonical/anbox-streaming-sdk pull request #42
Opened 2024-06-26 09:25 UTC by lorumic

# Done

- Determine architecture automatically by querying the `/nodes` endpoint of AMS.
- Add e2e tests for stream disconnect + `done` callback.
- Add e2e tests for VHAL: `vhalReady` callback, `getAllVhalPropConfigs`, `getVhalProperties`, `setVhalProperties` methods.

Until #37 is merged, you can see the test passing [here](https://github.com/lorumic/anbox-streaming-sdk/actions/runs/9676912820/job/26697489529).

Fixes [WD-11812](https://warthogs.atlassian.net/browse/WD-11812)

2024-06-26 09:51 UTC, ajanon reviewed
Just one small question: with this change, we would only be running e2e tests against AAOS 13, right?
Should we run these tests against multiple LXD images versions?
I'm not sure if it's too useful, but I would like to have other opinions.

2024-06-26 09:55 UTC, lorumic commented
> Just one small question: with this change, we would only be running e2e tests against AAOS 13, right? Should we run these tests against multiple LXD images versions? I'm not sure if it's too useful, but I would like to have other opinions.

For now, I'm focusing on having a single image downloaded, and running tests on a session created from that one only. This is to make the tests run reasonably fast. If there is an actual need of running on different images, technically we could do that, however I don't know if it's in the scope of the e2e tests, as it seems more about "testing the images" rather than "testing the features of the Anbox streaming SDK end-to-end". However, this is just my point of view, so I'm happy to hear other opinions and change the workflow accordingly. :)

2024-06-26 10:09 UTC, ajanon approved these changes
LGTM then, thanks!

2024-06-26 10:30 UTC, morphis commented
> For now, I'm focusing on having a single image downloaded, and running tests on a session created from that one only. This is to make the tests run reasonably fast. If there is an actual need of running on different images, technically we could do that, however I don't know if it's in the scope of the e2e tests, as it seems more about "testing the images" rather than "testing the features of the Anbox streaming SDK end-to-end". However, this is just my point of view, so I'm happy to hear other opinions and change the workflow accordingly. :)

There are quite a few nuances we do not necessarily can test with every image (e.g. I doubt we have virtual keyboard support for AAOS atm). I think you definitely want one per image variant (android, aaos and generic as well once we start officially supporting that).

2024-06-26 10:31 UTC, morphis commented on .github/workflows/e2e.yaml
> +        sudo microbox.amc image add jammy:aaos13:amd64 jammy:aaos13:amd64
See comment on the PR. I think we start switching the image we should run the same tests for both AAOS and Android as there are different nuances we want to test as well going forward

2024-06-26 10:34 UTC, morphis requested changes

2024-06-26 10:34 UTC, morphis commented on js/tests/e2e/tests/vhal.spec.js
> +  await page.waitForFunction(
What about `isVhalAvailable`?

It would also be nice to test the opposite case where we do not have the VHAL (e.g. with `jammy:android12`) and make sure things are correctly reported. Given that is currently what is deployed the most by our users I think that definitely deserves a test case. However you may want to split this in a future story if it expands the scope of what you're currently working on.

2024-06-26 10:38 UTC, morphis commented
@lorumic I've merged https://github.com/canonical/anbox-streaming-sdk/pull/37, if you update the PR we should be able to get tests running now.

2024-06-26 10:55 UTC, lorumic commented on js/tests/e2e/tests/vhal.spec.js
> +  await page.waitForFunction(
> What about `isVhalAvailable`?

No need to check for that when you have the `vhalReady` callback - which is anyway a better and more reliable way to test for VHAL capability asynchronously.

> It would also be nice to test the opposite case where we do not have the VHAL (e.g. with `jammy:android12`) and make sure things are correctly reported. Given that is currently what is deployed the most by our users I think that definitely deserves a test case. However you may want to split this in a future story if it expands the scope of what you're currently working on.

What does this mean? Test that `isVhalAvailable()` returns `false` when using an AOSP image? That's tricky because it will always be false at the beginning, but this doesn't necessarily mean that it never becomes true. Or are you suggesting to wait for a given time to check that it doesn't become true, and if it doesn't then we're good?

2024-06-26 11:01 UTC, lorumic commented on .github/workflows/e2e.yaml
> +        sudo microbox.amc image add jammy:aaos13:amd64 jammy:aaos13:amd64
For now, we're not testing those nuances, are we? When we'll do that, we can consider downloading different images, increase the timeouts so that the download can finish, and test those nuances.

But for now, that would only mean unnecessarily increase the test run time for no added benefit, since what we're testing is 100% equivalent on AAOS, AOSP and probably even generic.

2024-06-26 12:07 UTC, lorumic commented
@morphis @ajanon 

I'm laying the ground for when we'll need to test different features on different images. For this purpose, I tested locally the parallel creation of an AOSP-based app + session and AAOS-based ones. Thanks to the parallel execution, it should not take too much additional time - the test is still running, though, and we'll have to see how it behaves on the runner, since we'd also need to download both images there, unlike locally where they are already downloaded.

If that works well, I will run the join + disconnect stream test on the AOSP session, and the VHAL test (which includes join + disconnect anyway) on the AAOS one. Anything else, I'd like to keep as a future addition so as not to grow too much the scope of this task, which was planned to comprise only what is listed in the "Done" section of the PR description above.

Does that sound reasonable to you?

2024-06-26 13:12 UTC, adglkh commented on js/tests/e2e/tests/vhal.spec.js
> +  expect(setProperties.length).toBe(TARGET_VHAL_PROPS.length);
Can we read and verify the values again after modifying them?

2024-06-26 13:30 UTC, lorumic commented on .github/workflows/e2e.yaml
> +        sudo microbox.amc image add jammy:aaos13:amd64 jammy:aaos13:amd64
Thanks for your comment Gary. I have partly implemented the changes requested by @ajanon and @morphis, see [this](https://github.com/canonical/anbox-streaming-sdk/pull/42#issuecomment-2191527283) comment. This allows to test both AOSP and AAOS images (on Android 13 for now, but please do let me know if you prefer e.g. AOSP 12 and I can easily change it in the workflow). I think this can be a good start, and the overhead in terms of test run time is just +3 minutes.

2024-06-26 14:54 UTC, lorumic commented on js/tests/e2e/tests/vhal.spec.js
> +  expect(setProperties.length).toBe(TARGET_VHAL_PROPS.length);
Thanks for the suggestion @adglkh, the check has now been implemented. Test run: https://github.com/lorumic/anbox-streaming-sdk/actions/runs/9681782608

2024-06-26 15:23 UTC, morphis requested changes

2024-06-26 15:23 UTC, morphis commented on js/tests/e2e/tests/vhal.spec.js
> +  await page.waitForFunction(
The main part we need to cover is that in case that we do not expect any VHAL capabilities from the image we should get sane results from all the API calls the SDK has. That starts with `isVhalAvailable` but applies for the other methods as well.

2024-06-26 15:23 UTC, morphis commented on js/tests/e2e/tests/vhal.spec.js
> +  await page.waitForFunction(
> No need to check for that when you have the vhalReady callback - which is anyway a better and more reliable way to test for VHAL capability asynchronously.

I agree. However we should still check that `isVhalAvailable` gives us the expected value at that point. It's a public API method so to ensure we have full coverage we should call it and match against our expectation.

2024-06-26 17:56 UTC, morphis approved these changes
LGTM

2024-06-26 17:56 UTC, morphis commented on js/tests/e2e/tests/vhal.spec.js
> +test("VHAL methods on an AOSP session", async ({ page }) => {
Nice, thanks a lot for doing this!

2024-06-27 00:54 UTC, adglkh approved these changes
LGTM

2024-06-27 12:18 UTC, ajanon approved these changes
LGTM

2024-06-28 12:57 UTC, morphis commented
@lorumic I think we're blocked on https://github.com/canonical/anbox-streaming-sdk/pull/43 before we can merge this one?

2024-06-28 12:58 UTC, lorumic commented
> @lorumic I think we're blocked on #43 before we can merge this one?

Yes indeed, I was hoping to test the outcome of #43 on this one before merging it.

2024-07-02 08:18 UTC, lorumic commented
As discussed with @edlerd, there are changes to the workflow in this PR which won't get picked up, making the tests still fail. I have another addition of e2e tests in the works (based on this one) which doesn't make changes to the workflow, so we can test the CI changes on that one once I open it. You can check that the tests for this branch are passing by looking at the fork [run](https://github.com/lorumic/anbox-streaming-sdk/actions/runs/9757080832/job/26928703020#step:10:1882). So I'm merging this now.

2024-07-02 08:18 UTC, merged