fix(ci) ensure a branch from a forked pr is available in ci
canonical/anbox-streaming-sdk pull request #43
Opened 2024-06-26 11:04 UTC by edlerd

We would previously checkout the canonical repo, but for a PR from a
 fork we need to checkout the fork repo instead.
 WD-12279

2024-06-26 11:42 UTC, morphis requested changes

2024-06-26 11:42 UTC, morphis commented on .github/workflows/e2e.yaml
> +       repository: ${{ github.event.pull_request.head.repo.full_name }}
Doesn't this mean we run on what the latest state in the remote repository is? Github actually does a merge with the target repository for the checkout you test in so you run a combined state in case that the PR is not up-to-date. See the following from the CI execution of this PR:

![image](https://github.com/canonical/anbox-streaming-sdk/assets/433752/728f83ea-9355-4fa9-98dc-71addc0f57a8)

Specifically the last line is important: `HEAD is now at e2b8467 Merge 9b296ed4db32c448e46a14055e6740051bb1c457 into b63a98e8b7607e7dbcbb5d24cc9d04c393292088`

It checks out commit e2b8467 whereas 9b296ed4db32c448e46a14055e6740051bb1c457 is top of your to be merged branch and b63a98e8b7607e7dbcbb5d24cc9d04c393292088 is what is latest in the repository on the main branch. With this change here we will checkout 9b296ed4db32c448e46a14055e6740051bb1c457 and ignore any changes in main.

2024-06-26 12:26 UTC, edlerd commented on .github/workflows/e2e.yaml
> +       repository: ${{ github.event.pull_request.head.repo.full_name }}
If found [this](https://github.com/actions/checkout/issues/518#issuecomment-890401887), which suggests relying on `ref: "${{ github.event.pull_request.merge_commit_sha }}"`, because there is a race when a run from outside collaborators get approved. The external PR might be modified between approval and the GH action doing the checkout of the external branch. Relying on the merge sha prevents this race attack.

2024-06-26 12:34 UTC, edlerd commented on .github/workflows/e2e.yaml
> +       repository: ${{ github.event.pull_request.head.repo.full_name }}
Changed this to `ref: "${{ github.event.pull_request.merge_commit_sha }}"`, which is the merge hash on the target repo for the open PR. this is being discussed in [this thread](https://github.com/actions/checkout/issues/518), with some concerns the sha might be out of date. I think in that case, we'd need to keep in mind to trigger CI a 2nd time.

2024-06-26 13:03 UTC, morphis commented on .github/workflows/e2e.yaml
> +       repository: ${{ github.event.pull_request.head.repo.full_name }}
@edlerd what about doing the merge ourself? We have the candidate branch and know the target. Doing a `git merge ...` should be straight forward if we start with a target checkout and merge the candidate branch in?

2024-06-28 16:17 UTC, edlerd commented on .github/workflows/e2e.yaml
> +       repository: ${{ github.event.pull_request.head.repo.full_name }}
I agree, we can bundle our own merge strategy in the workflow. The commit sha is the only reliable way to ensure we run exactly the code that was reviewed by us. Relying on the PR branch name opens an attack vector to run code that was not reviewed. The user can push to their fork-branch after things got reviewed by us and before the workflow is running.

2024-07-01 19:59 UTC, morphis approved these changes
LGTM

2024-07-01 19:59 UTC, morphis commented on .github/workflows/e2e.yaml
> +       repository: ${{ github.event.pull_request.head.repo.full_name }}
Thanks for the explanation @edlerd !

2024-07-01 19:59 UTC, merged