feat(tests): visual tests for input events: touch, keyboard, long press
canonical/anbox-streaming-sdk pull request #45
Opened 2024-07-02 17:17 UTC by lorumic

Work in progress - cannot make the long press work on Firefox.

2024-07-08 08:36 UTC, adglkh requested changes
Can we create symbolic links pointing to the Chromium screenshots when Firefox is in use, given that they are pretty much the same?

2024-07-08 08:56 UTC, lorumic commented
> Can we create symbolic links pointing to the Chromium screenshots when Firefox is in use, given that they are pretty much the same?

@adglkh Thanks for the suggestion. It totally makes sense, and I have done that. Please note that for one of them we cannot do it, as for some reason it has a small difference between Chromium and Firefox by default (the microphone button on the right of the search bar).

2024-07-08 10:58 UTC, adglkh approved these changes
LGTM

2024-07-08 16:17 UTC, edlerd commented on js/tests/e2e/playwright.config.js
> +            "media.videocontrols.picture-in-picture.video-toggle.enabled": false,
Can you add a comment why we disable this?

2024-07-08 16:17 UTC, edlerd commented on js/tests/e2e/tests/visual.spec.js-snapshots/text-input-firefox-linux.png
> +text-input-chromium-linux.png
Is there a way to share the screenshots without having the dedicated files for firefox and chromium? It seems they are all the same as the ff screens reference the chromium screenshots.

2024-07-08 16:27 UTC, lorumic commented on js/tests/e2e/tests/visual.spec.js-snapshots/text-input-firefox-linux.png
> +text-input-chromium-linux.png
The screenshot filename follows a specific pattern that Playwright handles and expects to find:

`screenshot-name-browser-osname`

Where only the `screenshot-name` is the part that you're allowed to customise, i.e. the string that you pass as a parameter of the `toHaveScreenshot` function (plus the extension). The browser name and OS name (linux, darwin, etc) are managed by Playwright and cannot be customised.

2024-07-08 16:45 UTC, lorumic commented on js/tests/e2e/playwright.config.js
> +            "media.videocontrols.picture-in-picture.video-toggle.enabled": false,
Sure thing, that's done

2024-07-09 06:50 UTC, edlerd approved these changes
LGTM, thanks for adding those :+1:

2024-07-09 07:59 UTC, merged