Add and integrate Snapdragon Game Super Resolution(SGSR) into js sdk
canonical/anbox-streaming-sdk pull request #59
Opened 2024-09-14 08:45 UTC by adglkh

Snapdragon™ Game Super Resolution(SGSR), which integrates upscaling
and sharpening in one single GPU shader pass. The algorithm uses a
12-tap Lanczos-like scaling filter and adaptive sharpening filter,
which presents smooth images and sharp edges. For more details:
    
     https://github.com/SnapdragonStudios/snapdragon-gsr
    
This change adds and integrates SGSR, this single GPU shader pass
into the streaming js sdk, and usd by default for the time being.
    
NOTE: for now, FSR is still kept in the source for reference.
In the end, we will choose the best upscaling algorithm from all
available options after benchmarking and comparing performance and
quality, and only ship the best one in the streaming SDK.

2024-09-14 08:52 UTC, adglkh commented
Let's hold off on merging this until we've discussed how to manage multiple shaders in the main branch or decide whether to keep FSR before we reach a conclusion after benchmarking and comparing the performance and quality of all available upscaling algorithms (FSR, Anime4K, SGSR), choose the best one, and use it in our JS SDK.

2024-09-19 11:32 UTC, morphis requested changes
Can we split out SGSR integration into an example? That way we can merge and then defer the decision to a later point. Wdyt?

2024-09-19 12:03 UTC, adglkh commented
> Can we split out SGSR integration into an example? That way we can merge and then defer the decision to a later point. Wdyt?

A: hmm, sorry I don't get it. What do you mean by `split out SGSR integration into an example`?

2024-09-19 12:38 UTC, morphis commented
@adglkh we don't want to switch the actual shader implementation in the SDK yet. So what we can do instead is write an example application using SGSR and add that to https://github.com/canonical/anbox-streaming-sdk/tree/main/examples/js as part of this PR. Then we have an example demonstrating the use and have no pending PR.

2024-09-19 12:52 UTC, adglkh commented
> @adglkh we don't want to switch the actual shader implementation in the SDK yet. So what we can do instead is write an example application using SGSR and add that to https://github.com/canonical/anbox-streaming-sdk/tree/main/examples/js as part of this PR. Then we have an example demonstrating the use and have no pending PR.

A: okay, that makes sense to me.

2024-09-20 09:58 UTC, adglkh commented
The image is broken, which has blocked e2e testing. Let's wait for the new image to be built and cached today in the next run.

2024-09-20 19:57 UTC, morphis approved these changes
LGTM

2024-10-07 06:52 UTC, ajanon approved these changes
LGTM, just one question

2024-10-07 06:52 UTC, ajanon commented on examples/js/sgsr.html
> +    <title>Anbox Streaming SDK Example - Enable video upscaling with Snapdragon™ Game Super Resolution(SGSR) </title>
Random question: do we need an agreement from them to use this name?
Or put a disclaimer (e.g. 'This trademark is possessed by...')

2024-10-23 02:48 UTC, adglkh commented on examples/js/sgsr.html
> +    <title>Anbox Streaming SDK Example - Enable video upscaling with Snapdragon™ Game Super Resolution(SGSR) </title>
Thanks @ajanon , would you mind taking another look?

2024-10-23 09:08 UTC, ajanon approved these changes
LGTM

2024-10-23 09:43 UTC, merged