fix(readme): add instructions to run unit and e2e tests
canonical/anbox-streaming-sdk pull request #82
Opened 2024-11-06 15:29 UTC by lorumic

Added instructions to the README of the repo, to explain how to run unit tests and end-to-end tests.

2024-11-06 16:27 UTC, keirthana requested changes
Some minor comments

2024-11-06 16:27 UTC, keirthana commented on README.md
> +Both these folders contain a `run-tests.sh` script. You just need to run this script to start the tests. However, to run end-to-end tests you need also an Anbox Cloud back-end. The easiest way to set
```suggestion
Both these folders contain a `run-tests.sh` script that you can run to start the tests. However, to run end-to-end tests, you also need an Anbox Cloud deployment. The easiest way to set up one is by using the [Anbox Cloud Appliance](https://documentation.ubuntu.com/anbox-cloud/en/latest/tutorial/installing-appliance/).
```

2024-11-06 16:27 UTC, keirthana commented on README.md
> +Once the back-end is ready, follow these steps to run the end-to-end tests:
```suggestion
Once the appliance is ready, follow these steps to run the end-to-end tests:
```

2024-11-06 16:43 UTC, lorumic commented
Thanks for the great suggestions @keirthana - I have addressed your comments [here](https://github.com/canonical/anbox-streaming-sdk/compare/57bec1d9c35c8852eda6d5d7ced374f9bc8d3970..75a5505971419f199fe7150aad464371f34ed4f7).

2024-11-06 18:45 UTC, morphis approved these changes
LGTM

2024-11-07 02:03 UTC, adglkh approved these changes
LGTM

2024-11-07 09:49 UTC, ajanon approved these changes
LGTM

2024-11-07 15:50 UTC, keirthana approved these changes
Thanks, LGTM

2024-11-07 16:20 UTC, merged